/**
 * @file Itertools.hpp
 */

#include "Itertools/Accumulate.hpp"
#include "Itertools/Chain.hpp"
#include "Itertools/Combinations.hpp"
#include "Itertools/CombinationsWithReplacement.hpp"
#include "Itertools/Compress.hpp"
#include "Itertools/Count.hpp"
#include "Itertools/Cycle.hpp"
#include "Itertools/Dropwhile.hpp"
#include "Itertools/Filter.hpp"
#include "Itertools/Filterfalse.hpp"
#include "Itertools/Groupby.hpp"
#include "Itertools/Islice.hpp"
#include "Itertools/Permutations.hpp"
#include "Itertools/Product.hpp"
#include "Itertools/Range.hpp"
#include "Itertools/RangeView.hpp"
#include "Itertools/Repeat.hpp"
#include "Itertools/Starmap.hpp"
#include "Itertools/Takewhile.hpp"
#include "Itertools/Tee.hpp"
#include "Itertools/Zip.hpp"
#include "Itertools/ZipLongest.hpp"
